apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "tsmentjhon@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "kmeq noun rfqx hasd"
type: Opaque
